dist: bionic
language: go

services:
  - docker

go:
  - 1.15.x
  - tip

matrix:
  allow_failures:
    - go: tip

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

# skip non-trunk PMM-XXXX/SAAS-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{3,5}/
    - /^SAAS\-\d{2,5}/

go_import_path: github.com/percona/pmm-update

env:
  global:
    - CODECOV_ENV=PMM_SERVER_IMAGE

    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "enjXZPPLcL1XySF+ja2Su5WmXa81e4sLKpsdsER2NnACAXCfiza9keZaGyWCsmsF1r6ZMXkjj1Chtj2PSWiGiwh9WzSt69psamulj3F3cGYrsf7eP1CS8dKBRKQZ+P3RizE3NXnd8Nr47eUpwkrPPNikry5bzrU6cDj2omifZ32O+iHwTgBxRYKZi/npYxal6bDio+eA0NCSoDMRuEeh10JbaYhxJ7nHY/qI31QAv7X1F59lPG/oARXp5hPb7/suvU/UXNvLLtKFv1BMLzLfZ+1WidSxjmveDGiTUVK9auJK9ihNRng0PQON2XgNmPE1CpDlzq4Sg1oPIv9i5lUPoxb03+jN6Ef63bthrOBKU31ZDDsSzAiTelOeIMQNxfolw1e8FHpSkG9O7UqNiTXvvY+3SOUW8uOj/ZUuv4E98oTfdZeijGyQweDz2Lqcot8shtTdAdJKGnCWnEyn0KjnszeVGmtSePD0z7Zif0fySYXR0iOuqsGofArO2jbXFVeZxUrLmlzHwRBbvogdYLh0mZ3WRTvZt4VwynPixwH1323oXk0y8ZIiy4Tjcu0l9p3ymkjD3UduCnR834gCRHTOsucKjjkkRrC7Y4UY/6GARghJKELBT/z0mrIMnTnAFso6XiybHw6s6hbSR8n41suyfoUKdl5NwRaXyQC2deuqfcU="

  matrix:
    - PMM_SERVER_IMAGE=percona/pmm-server:2.0.0          # oldest production version
    - PMM_SERVER_IMAGE=percona/pmm-server:2              # latest production version
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest  # latest development version

before_install:
  - docker-compose up -d
  - docker exec pmm-update-server /root/go/src/github.com/percona/pmm-update/.devcontainer/install-dev-tools.sh

install: skip

before_script:
  - make init
  - make format
  - git status
  - git diff --exit-code

script:
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update ci-reviewdog
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update install

  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update test-cover
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update test-race

  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update check

  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update
    run-race-cover RUN_FLAGS='-debug -check'

  # ignore first possible self-update exit
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update
    run-race-cover RUN_FLAGS='-debug -perform -playbook=/root/go/src/github.com/percona/pmm-update/ansible/playbook/tasks/update.yml'
    || true
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update
    run-race-cover RUN_FLAGS='-debug -perform -playbook=/root/go/src/github.com/percona/pmm-update/ansible/playbook/tasks/update.yml'

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f cover.out -F cover -X fix
  - ./codecov -f *.runcover.out -F runcover -X fix

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: wli+4QuiaV5Z75W2zXdy6OWmXgSCYJb49cOGy1Nqez6qWMxPar7f0uugd6t6CvABlrEeIbKwnE/J4MsmbASkTMS9EpMRR8/UslvnJeuOQ8lml7+9EUOGO5EskohnC5xKQyX+ujqfaRrb1Fv22xjCNLASvjLYSXMuyr2jn6ddd3/+YaJZ3Osx/EmXoTgvr+FiUmiqvNPUcGjIg4vhbFwzYwQA+k6KU+zPVYYlF+OOsVLDVy70gyuHnkfJ7YbbnVtBg++OwkBsppC5vwBJFAeX1iHg5m93bD6n9wTea/68bPNKg/1zA7ymqqNDZEmWQX15P74By3yIpY3FD38CywHorBWUWECTf+34nnl97tL23M5WuMERqtWsb5/oqoXwy9uObTQr3m9B0UzoClCoFjlHRXjZDom14k4yb2KeK9VWJErqv3ZdjWEVMQx0QtecsJE1829w6xYSdGHZ36g8HWaY/Lz6Or2ZgFn5l7+wkYsY9H1Dp46WuM+9nQkG9KkAfsMr4iOwm0+FnzrxuZ0TFKej4NNDeJvpRfD6uuFtGl0g5I6FJv9vKZUK66eacVEdlEm/J0VUxeYBP7td/3PE5phBbbKyoU3Qa55V1JXXkmrBmzQtjCaNRegPABPQTUWJKmUKG3uf3/1syS3y6kWjkOAxCUvqZiTVd4OfnezbN7O8jXU=
