dist: xenial
language: go

services:
  - docker

go:
  - 1.12.x
  # TODO - master

matrix:
  allow_failures:
    - go: master

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  matrix:
    - PMM_SERVER_IMAGE=perconalab/pmm-server:2.0.0-beta4
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

before_install:
  - docker-compose up -d
  - docker exec pmm-update-server /root/go/src/github.com/percona/pmm-update/.devcontainer/install-dev-tools.sh

install:
  - cd pmm2-update

  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check

before_script:
  - make init
  - make format
  - git status
  - git diff --exit-code

script:
  - docker exec pmm-update-server make -C /root/go/src/github.com/percona/pmm-update/pmm2-update install test

  # - make test-cover
  # - make test-race

  # - make run-race-cover

  - make check

after_success:
  # - curl https://codecov.io/bash > codecov
  # - chmod +x codecov
  # - ./codecov -f cover.out -F cover -X fix
  # - ./codecov -f crosscover.out -F crosscover -X fix

notifications:
  email: false
