dist: xenial
language: go

services:
  - docker

go:
  - 1.12.x
  # TODO - master

matrix:
  allow_failures:
    - go: master

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  matrix:
    - PMM_SERVER_IMAGE=perconalab/pmm-server:dev-latest

before_install:
  - cd src/github.com/percona/pmm-update
  - pwd
  - go env

  - docker-compose up -d

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  # - dep check
  - dep ensure -v

  - pwd

before_script:
  - make init
  # - make gen
  - make format
  # - git status
  # - git diff --exit-code

script:
  # for main_test.go
  - make install

  - make test-cover
  - make test-race

  - make run-race-cover

  - make check

after_success:
  # - curl https://codecov.io/bash > codecov
  # - chmod +x codecov
  # - ./codecov -f cover.out -F cover -X fix
  # - ./codecov -f crosscover.out -F crosscover -X fix

notifications:
  email: false
