---
version: '3'
services:
  pmm-server:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-update-server
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443
    volumes:
      - .:/pmm-update
