---
# This playbook contains tasks shared by AMI, OVF, and Docker image build processes.
# It should be frozen at the moment of 2.0 release.

- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - debug:
