---
- name: Remove old clickhouse packages
  yum:
    state: absent
    name:
      - percona-clickhouse-client
      - percona-clickhouse-server
      - percona-clickhouse-common-static
      - percona-clickhouse-server-common

- name: Disable clickhouse-server in systemd
  when: not is_container
  service:
    name: clickhouse-server
    state: stopped
    enabled: no

- name: Create clickhouse data directory
  file: 
    path: "/srv/clickhouse" 
    state: directory
    owner: root
    group: pmm

- name: Ensure clickhouse repo GPG key imported
  rpm_key:
    state: present
    key: "https://repo.clickhouse.tech/CLICKHOUSE-KEY.GPG"

- name: Ensure clickhouse repo installed
  yum_repository:
    name: clickhouse
    file: clickhouse
    description: "Clickhouse repo"
    baseurl: "https://repo.clickhouse.tech/rpm/stable/x86_64/"
    enabled: yes
    gpgcheck: 1
    gpgkey: "https://repo.clickhouse.tech/CLICKHOUSE-KEY.GPG"

- name: Ensure clickhouse package installed
  yum:
    name:
      - clickhouse-client-{{ clickhouse_version}}
      - clickhouse-server-{{ clickhouse_version}}
      - clickhouse-common-static-{{ clickhouse_version}}
    state: installed
  ignore_errors: '{{ ansible_check_mode }}' # We don't have clickhouse repo when we run ansible with --check

- name: Copy clickhouse config to image
  copy:
    src: config.xml
    dest: /etc/clickhouse-server/config.xml
    mode: 0600

- name: Restart clickhouse
  command: supervisorctl {{ item }} clickhouse
  changed_when: True
  loop:
    - "stop"
    - "remove"
    - "add"

- name: Clickhouse                | Wait for clickhouse start
  wait_for:
    port: 8123
    state: present
    delay: 30
    timeout: 60

- name: Cickhouse                 | Create ClickHouse database
  command: clickhouse-client --host 127.0.0.1 --query="CREATE DATABASE IF NOT EXISTS pmm"
  changed_when: False

- name: Cickhouse                 | Show ClickHouse database
  command: clickhouse-client --host 127.0.0.1 --query="SHOW DATABASES"
  changed_when: False
